# 50_assemble_manuscript.R — assemble the section drafts into one manuscript
#
# Usage: Rscript R/50_assemble_manuscript.R
#
# Reads the section drafts in docs/manuscript/, strips their YAML front matter, per-section
# drafting notes and per-section reference lists, concatenates them in manuscript order, and
# renumbers every citation in order of first appearance (NLM/Vancouver). Outstanding [CONFIRM]
# items are collected into a single note at the top. Writes manuscript_draft.md (+ .docx when
# pandoc is available). Re-run after editing any section: the section files stay the source.

source(here::here("R", "00_setup.R"))

man_dir <- here("docs", "manuscript")
sections <- c("abstract_background_draft.md", "methods_draft.md",
              "results_rq1_rq2_draft.md", "results_rq3_draft.md", "discussion_draft.md")
stopifnot(all(file.exists(file.path(man_dir, sections))))

TITLE <- "Missing-data methods and equity estimates of child undernutrition: a methodological study using the 2021 Madagascar Demographic and Health Survey"

read_section <- function(f) {
  x <- readLines(file.path(man_dir, f), warn = FALSE, encoding = "UTF-8")
  # drop YAML front matter
  fm <- which(x == "---")
  if (length(fm) >= 2 && fm[1] == 1) x <- x[(fm[2] + 1):length(x)]
  # drop drafting-note block quotes (kept separately as [CONFIRM] items)
  x <- x[!startsWith(x, ">")]
  # split off the section's own reference list
  ref_start <- grep("^## References", x)
  refs <- character(0)
  if (length(ref_start)) {
    refs <- x[(ref_start[1] + 1):length(x)]
    x <- x[seq_len(ref_start[1] - 1)]
  }
  # collapse runs of blank lines
  keep <- !(x == "" & c(FALSE, head(x, -1) == ""))
  list(body = x[keep], refs = refs)
}

parts <- lapply(sections, read_section)
names(parts) <- sections

# ---- reference pool: number -> text (from every section's list) ----------------------------
ref_lines <- unlist(lapply(parts, `[[`, "refs"), use.names = FALSE)
ref_lines <- ref_lines[nzchar(trimws(ref_lines))]
starts <- grep("^[0-9]+[.] ", ref_lines)
stopifnot(length(starts) > 0)
ends <- c(tail(starts, -1) - 1, length(ref_lines))
ref_pool <- lapply(seq_along(starts), function(i) {
  block <- ref_lines[starts[i]:ends[i]]
  num <- as.integer(sub("^([0-9]+)[.].*$", "\\1", block[1]))
  text <- paste(trimws(c(sub("^[0-9]+[.] ", "", block[1]), tail(block, -1))), collapse = " ")
  list(num = num, text = text)
})
old_num <- vapply(ref_pool, function(r) r$num, integer(1))
old_text <- vapply(ref_pool, function(r) r$text, character(1))
stopifnot(!anyDuplicated(old_num))

# ---- body in manuscript order ---------------------------------------------------------------
body <- c(
  paste("#", TITLE), "",
  parts[["abstract_background_draft.md"]]$body, "",
  parts[["methods_draft.md"]]$body, "",
  parts[["results_rq1_rq2_draft.md"]]$body, "",
  # RQ3 continues the same Results section: drop its own "## Results (continued)" heading
  parts[["results_rq3_draft.md"]]$body[!grepl("^## Results", parts[["results_rq3_draft.md"]]$body)], "",
  parts[["discussion_draft.md"]]$body
)

# move the Declarations section (drafted inside Methods) to the end
decl_start <- grep("^## Declarations", body)
if (length(decl_start)) {
  nxt <- grep("^## ", body)
  decl_end <- nxt[nxt > decl_start[1]]
  decl_end <- if (length(decl_end)) decl_end[1] - 1 else length(body)
  decl <- body[decl_start[1]:decl_end]
  body <- c(body[-(decl_start[1]:decl_end)], "", decl)
}

# ---- renumber citations in order of first appearance -----------------------------------------
cite_pat <- "\\[[0-9]+(,[0-9]+)*\\]"
hits <- regmatches(body, gregexpr(cite_pat, body))
order_seen <- unique(unlist(lapply(unlist(hits), function(tok) {
  as.integer(strsplit(gsub("[][]", "", tok), ",")[[1]])
})))
missing_refs <- setdiff(order_seen, old_num)
if (length(missing_refs)) stop("cited but not in any reference list: ", paste(missing_refs, collapse = ", "))
unused <- setdiff(old_num, order_seen)
map <- setNames(seq_along(order_seen), as.character(order_seen))

body <- vapply(body, function(line) {
  m <- gregexpr(cite_pat, line)[[1]]
  if (m[1] == -1) return(line)
  toks <- regmatches(line, gregexpr(cite_pat, line))[[1]]
  new <- vapply(toks, function(tok) {
    nums <- as.integer(strsplit(gsub("[][]", "", tok), ",")[[1]])
    paste0("[", paste(map[as.character(nums)], collapse = ","), "]")
  }, character(1))
  regmatches(line, gregexpr(cite_pat, line)) <- list(new)
  line
}, character(1), USE.NAMES = FALSE)

ref_out <- paste0(seq_along(order_seen), ". ", old_text[match(order_seen, old_num)])

# ---- outstanding items ------------------------------------------------------------------------
confirms <- grep("[[]CONFIRM", body, value = TRUE)
note <- c(
  "> **Assembly note (delete before submission).** Generated by `R/50_assemble_manuscript.R` from the",
  paste0("> section drafts in `docs/manuscript/`; edit those, not this file. Citations were renumbered in ",
         "order of first appearance (", length(order_seen), " references)."),
  paste0("> Outstanding author checks marked in the text: ", length(confirms),
         ". All references still require verification before submission."),
  "")

writeLines(c(note, body, "", "## References", "", ref_out),
           file.path(man_dir, "manuscript_draft.md"), useBytes = TRUE)

message("50: assembled manuscript_draft.md — ", length(order_seen), " references, ",
        length(confirms), " [CONFIRM] items",
        if (length(unused)) paste0("; unused references dropped: ", paste(unused, collapse = ", ")) else "")

# ---- Word export (pandoc; RStudio's copy if not on PATH) ---------------------------------------
if (!rmarkdown::pandoc_available()) {
  rs <- "C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools"
  if (dir.exists(rs)) Sys.setenv(RSTUDIO_PANDOC = rs)
}
if (rmarkdown::pandoc_available()) {
  out <- file.path(man_dir, "manuscript_draft.docx")
  unlink(out)
  rmarkdown::pandoc_convert(input = normalizePath(file.path(man_dir, "manuscript_draft.md")),
                            from = "markdown+smart", output = normalizePath(out, mustWork = FALSE))
  message("50: wrote manuscript_draft.docx")
}
